### ISSUE TITLE
Connection Pool Errors

### ISSUE THREAD

**Issue by AdamBrodzinski** [elixir-mongo/mongodb#101]
Hello,

I've been using this library with poolboy in production for a couple of days and just received this error. I'm not sure what my next step should be. My first thought was to increase the `timeout` or `pool_timeout` (note this app isn't under heavy load, 1-2 users at max).

Should I remove poolboy and make the connection for each query? I'm mainly using it on every GraphQL request to fetch the user and add it as context for every request so it'll be used quite often.

Elixir Version: 1.3.2
MongoDB Version: 2.6.x (SSL not being used)
Host: Heroku for the app and Compose.io for MongoDB
(using Phoenix 1.2)

Any idea of what I should do next?

```
2017-02-01T01:41:50.691003+00:00 app[web.1]: 01:41:50.690 [error] Mongo.Protocol (#PID<0.333.0>) disconnected: ** (Mongo.Error) tcp recv: unknown POSIX error - :timeout
2017-02-01T01:41:50.692470+00:00 app[web.1]: 01:41:50.690 [error] Mongo.Protocol (#PID<0.337.0>) disconnected: ** (Mongo.Error) tcp recv: unknown POSIX error - :timeout
2017-02-01T01:41:50.692471+00:00 app[web.1]: 01:41:50.690 [error] Mongo.Protocol (#PID<0.335.0>) disconnected: ** (Mongo.Error) tcp recv: unknown POSIX error - :timeout
2017-02-01T01:41:50.723329+00:00 app[web.1]: 01:41:50.723 [error] GenServer #PID<0.333.0> terminating
2017-02-01T01:41:50.723332+00:00 app[web.1]: ** (RuntimeError) disconnect/2 not implemented
2017-02-01T01:41:50.723334+00:00 app[web.1]:     (mongodb) lib/db_connection.ex:240: Mongo.Protocol.disconnect/2
2017-02-01T01:41:50.723335+00:00 app[web.1]:     (db_connection) lib/db_connection/connection.ex:178: DBConnection.Connection.disconnect/2
2017-02-01T01:41:50.723335+00:00 app[web.1]:     (connection) lib/connection.ex:767: Connection.disconnect/3
2017-02-01T01:41:50.723335+00:00 app[web.1]:     (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
2017-02-01T01:41:50.723336+00:00 app[web.1]:     (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
2017-02-01T01:41:50.723336+00:00 app[web.1]:     (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
2017-02-01T01:41:50.723914+00:00 app[web.1]: 01:41:50.723 [error] GenServer #PID<0.337.0> terminating
2017-02-01T01:41:50.723915+00:00 app[web.1]: ** (RuntimeError) disconnect/2 not implemented
2017-02-01T01:41:50.723916+00:00 app[web.1]:     (mongodb) lib/db_connection.ex:240: Mongo.Protocol.disconnect/2
2017-02-01T01:41:50.723917+00:00 app[web.1]:     (db_connection) lib/db_connection/connection.ex:178: DBConnection.Connection.disconnect/2
2017-02-01T01:41:50.723918+00:00 app[web.1]:     (connection) lib/connection.ex:767: Connection.disconnect/3
2017-02-01T01:41:50.723918+00:00 app[web.1]:     (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
2017-02-01T01:41:50.723919+00:00 app[web.1]:     (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
2017-02-01T01:41:50.723920+00:00 app[web.1]:     (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

**Comment by ericmj** [comment]
There's an open PR for this that has some work left to do: https://github.com/ericmj/mongodb/pull/99.

**Comment by AdamBrodzinski** [comment]
@ericmj oh great thanks! Would you recommend not using Poolboy until that PR is closed? Or is this error something that won't affect the app in production?

**Comment by ericmj** [comment]
If the connection goes down, in some circumstances, the connection will not be automatically reconnected. Instead the connection process goes down, the supervisor will restart the process and the reconnection will happen. If your database is down for a while this has a chance of killing your supervisor depending on your supervisor settings.

**Comment by ankhers** [comment]
I believe this has been fixed in #116.

**Comment by nitinjain1105** [comment]
@ankhers 

I am using mongodb from an Elixir app and I am using - {:mongodb, "== 0.4.6"}

but I still see this issue, can you please help!

Mongo.Protocol (#PID<0.25313.3>) disconnected: ** (Mongo.Error) tcp recv: unknown POSIX error - :timeout

**Comment by ankhers** [comment]
@nitinjain1105 Can you please create a new issue?

**Comment by nitinjain1105** [comment]
@ankhers 

Created new issue [#274](https://github.com/ankhers/mongodb/issues/274)
