### ISSUE TITLE
Process crashes when running find_one/3 while mongodb is down

### ISSUE THREAD

**Issue by aaronrenner** [elixir-mongo/mongodb#189]
I've found an issue where running `Mongo.find_one/3` after mongodb has been shut down causes raises an error and causes the reconnection logic to crash.

Steps to recreate:
1. Ensure mongodb is up
2. Run Mongo.start_link to connect to the db. Here's my supervision tree at this point:
<img width="593" alt="screen shot 2018-01-25 at 1 34 02 pm" src="https://user-images.githubusercontent.com/120878/35411031-773408fa-01d4-11e8-8dc3-a378075ec3a8.png">
3. Shutdown the mongodb server. 
<img width="451" alt="screen shot 2018-01-25 at 1 40 45 pm" src="https://user-images.githubusercontent.com/120878/35411261-62fcecc0-01d5-11e8-982d-b4f0c1ec80e6.png">

4. Run `Mongo.find_one/3` while the connection is down. This returns the following error:
```
** (Protocol.UndefinedError) protocol Enumerable not implemented for :error. This protocol is implemented for: DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Mongo.AggregationCursor, Mongo.Cursor, Mongo.SinglyCursor, Range, Stream
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:116: Enumerable.reduce/3
    (elixir) lib/enum.ex:1850: Enum.reverse/1
    (elixir) lib/enum.ex:2599: Enum.to_list/1
    (mongodb) lib/mongo.ex:405: Mongo.find_one/4
```
5. Start back up the mongodb server. The supervision tree still looks like this:
<img width="409" alt="screen shot 2018-01-25 at 1 42 35 pm" src="https://user-images.githubusercontent.com/120878/35411335-a06bcbda-01d5-11e8-980e-dbcf8bdcde37.png">
and I still get the following error when running `Mongo.find_one/3`

```
** (Protocol.UndefinedError) protocol Enumerable not implemented for :error. This protocol is implemented for: DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Mongo.AggregationCursor, Mongo.Cursor, Mongo.SinglyCursor, Range, Stream
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:116: Enumerable.reduce/3
    (elixir) lib/enum.ex:1850: Enum.reverse/1
    (elixir) lib/enum.ex:2599: Enum.to_list/1
    (mongodb) lib/mongo.ex:405: Mongo.find_one/4
```

It seems like the only way to reconnect to mongo is to kill the `sso_mongo` process and let the supervisor restart it. Any ideas of how to work around this would be greatly appreciated.

**Comment by aaronrenner** [comment]
It looks like calling `Mongo.find/3` in this scenario also causes the crash in the supervision tree.

**Comment by safwanolaimat** [comment]
@aaronrenner how did you check if the connection with MongoDB is down or not before calling DB methods

**Comment by aaronrenner** [comment]
@husafwan I manually shutdown the mongo server on my laptop and then executed the code that tried to read from mongo (which called `Mongo.find_one/3` under the hood). The code failed, but to my surprise, when I started back up the mongo server my application wouldn't reconnect.

**Comment by ankhers** [comment]
That is strange. It works properly when the process is not supervised:

```elixir
iex(1)> {:ok, pid} = Mongo.start_link(database: "...")
{:ok, #PID<0.164.0>}
iex(2)> Mongo.find(pid, "users", %{}) |> Enum.to_list
[...] # Properly returned results
iex(3)> ### I stopped the mongo process in a different shell here
12:23:58.067 [error] Mongo.Protocol (#PID<0.166.0>) disconnected: ** (Mongo.Error) tcp async recv: unknown POSIX error - :closed

12:23:58.068 [error] Mongo.Protocol (#PID<0.171.0>) disconnected: ** (Mongo.Error) tcp async recv: unknown POSIX error - :closed

12:23:58.068 [error] Mongo.Protocol (#PID<0.166.0>) failed to connect: ** (Mongo.Error) tcp connect: connection refused - :econnrefused

12:23:58.068 [error] Mongo.Protocol (#PID<0.171.0>) failed to connect: ** (Mongo.Error) tcp connect: connection refused - :econnrefused

12:23:58.071 [error] Mongo.Protocol (#PID<0.175.0>) failed to connect: ** (Mongo.Error) tcp connect: connection refused - :econnrefused

12:24:08.073 [error] Mongo.Protocol (#PID<0.175.0>) failed to connect: ** (Mongo.Error) tcp connect: connection refused - :econnrefused

iex(3)> Mongo.find(pid, "users", %{}) |> Enum.to_list
** (Protocol.UndefinedError) protocol Enumerable not implemented for :error
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:116: Enumerable.reduce/3
    (elixir) lib/enum.ex:1636: Enum.reduce/3
    (elixir) lib/enum.ex:2346: Enum.to_list/1
iex(3)>
12:24:18.075 [error] Mongo.Protocol (#PID<0.175.0>) failed to connect: ** (Mongo.Error) tcp connect: connection refused - :econnrefused

### I restarted the mongo process in a different shell here

iex(3)> Mongo.find(pid, "users", %{}) |> Enum.to_list
[...] # properly returned results
```

But I am having the same issue you are having when it is a supervised process.

**Comment by ankhers** [comment]
After a bit of testing, it looks like the `Mongo.Monitor`'s are being removed from the topology state for some reason. Unfortunately I have not been able to dig into the why yet. But if anyone else would like to look into this, it would probably be a good idea to start looking in `Mongo.Topology`, specifically the `reconcile_servers/1` and `remove_address/2` functions.

**Comment by safwanolaimat** [comment]
how to check connection status ? @ankhers

**Comment by safwanolaimat** [comment]
after shutdown Mongo Server 
mongo process was killed 
`08:19:07.162 [error] Mongo.Protocol (#PID<0.223.0>) disconnected: ** (Mongo.Error) tcp recv: unknown POSIX error - :closed

08:19:07.163 [error] Mongo.Protocol (#PID<0.222.0>) disconnected: ** (Mongo.Error) tcp recv: unknown POSIX error - :closed

08:19:07.163 [error] Mongo.Protocol (#PID<0.228.0>) disconnected: ** (Mongo.Error) tcp recv: unknown POSIX error - :closed

08:19:07.163 [error] Mongo.Protocol (#PID<0.226.0>) disconnected: ** (Mongo.Error) tcp recv: unknown POSIX error - :closed

08:19:07.163 [error] Mongo.Protocol (#PID<0.227.0>) disconnected: ** (Mongo.Error) tcp recv: unknown POSIX error - :closed

08:19:07.163 [error] Mongo.Protocol (#PID<0.224.0>) disconnected: ** (Mongo.Error) tcp recv: unknown POSIX error - :closed

08:19:07.163 [error] Mongo.Protocol (#PID<0.225.0>) disconnected: ** (Mongo.Error) tcp recv: unknown POSIX error - :closed
 
08:19:07.164 [error] Mongo.Protocol (#PID<0.230.0>) disconnected: ** (Mongo.Error) tcp recv: unknown POSIX error - :closed
 
08:19:08.005 [error] GenServer #PID<0.214.0> terminating
** (RuntimeError) Connect raised a CaseClauseError error. The exception details are hidden, as
they may contain sensitive data such as database credentials.

    (mongodb) lib/mongo/protocol.ex:54: Mongo.Protocol.connect/2
    (db_connection) lib/db_connection/connection.ex:135: DBConnection.Connection.connect/2 
    (connection) lib/connection.ex:741: Connection.connect/3
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :timeout
State: Mongo.Protocol
 
08:19:08.006 [info]  Application mongotest exited: an exception was raised:
    ** (RuntimeError) Connect raised a CaseClauseError error. The exception details are hidden, as
they may contain sensitive data such as database credentials.

        (mongodb) lib/mongo/protocol.ex:54: Mongo.Protocol.connect/2
        (db_connection) lib/db_connection/connection.ex:135: DBConnection.Connection.connect/2
        (connection) lib/connection.ex:741: Connection.connect/3
        (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
        (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
`

**Comment by ankhers** [comment]
Would you mind testing master? I just pushed a fix for this issue and want to make sure that it works for you.

**Comment by aaronrenner** [comment]
I just tried it out and the reconnection logic works!

I am still seeing a `Protocol.UndefinedError` when calling `Mongo.find_one/4` while disconnected, but it no longer causes the reconnect logic to crash. I'll open that as a separate issue.

Thanks so much for the fix!

**Comment by ankhers** [comment]
I'm glad it worked for you!

**Comment by safwanolaimat** [comment]
hello 
is this problem related to your problem 

`** (FunctionClauseError) no function clause matching in :gen_server.cast/2    
    The following arguments were given to :gen_server.cast/2:
    
        # 1
        []
        # 2
        {:cancel_waiting, #Reference<0.3006240992.544735235.204473>}
    (stdlib) gen_server.erl:220: :gen_server.cast/2
    (poolboy) src/poolboy.erl:58: :poolboy.checkout/3
    (db_connection) lib/db_connection/poolboy.ex:41: DBConnection.Poolboy.checkout/2
    (db_connection) lib/db_connection.ex:928: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:750: DBConnection.run/3
    (db_connection) lib/db_connection.ex:1141: DBConnection.run_meter/3
    (db_connection) lib/db_connection.ex:644: DBConnection.execute/4
    (mongodb) lib/mongo.ex:417: Mongo.raw_find/5
`
